networks:
  custom_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1420
    ipam:
      config:
        - subnet: 172.16.24.0/24

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: always
    command: ["/bin/bash", "-c", "while true; do sleep 30; done"]
    volumes:
      - ./wg-conf:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
    networks:
      custom_network:
        ipv4_address: 172.16.24.3

  stalwart-mail:
    image: stalwartlabs/mail-server:v0.10.7
    container_name: stalwart-mail
    restart: always
    # ports:
    #   - "443:443"
    #   - "8080:8080"
    #   - "25:25"
    #   - "587:587"
    #   - "465:465"
    #   - "143:143"
    #   - "993:993"
    #   - "4190:4190"
    #   - "110:110"
    #   - "995:995"
    volumes:
      - ~/spool/stalwart-data:/opt/stalwart-mail
    # networks:
    #   custom_network:
    #     ipv4_address: 172.16.24.4
    network_mode: "service:wireguard"

  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    restart: always
    # ports:
    #   - "5354:53/udp"
    #   - "5354:53/tcp"
    #   - "953:953/tcp"
    volumes:
      - ~/spool/bind/etc:/etc/bind
      - ~/spool/bind/cache/bind:/var/cache/bind
      - ~/spool/bind/lib/bind:/var/lib/bind
      - ~/spool/bind/var/log:/var/log
    # networks:
    #   custom_network:
    #     ipv4_address: 172.16.24.53
    network_mode: "service:wireguard"
